server:
  port: 8080
  #  20m timeout
  servlet:
    session:
      timeout: 20m
spring:
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialec
  h2:
    console:
      enabled: true
      path: /db
      settings.trace: false
      settings.web-allow-others: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher

management:
  endpoints:
    web:
      exposure:
        include: health, mappings, info, metrics, threaddump, heapdump, shutdown, beans
  endpoint:
    health:
      show-details: always
info:
  app:
    name: Jyra Project Management Tool
    description: Project for the Spring v5 course
    version: 1.0-SNAPSHOT
